### PR TITLE
Support Rails 6.0, and drop 3.x, 4.x, 5.0 and 5.1

### PR DESCRIPTION
**Pull request by yhirano55**
## Summary

I've maintained CI configuration, because our legacy project depends on this gem. And we need to safely merge #279. It seems that framework versions is too old in travis config. So I've updated them.

## Support Rails versions:

- 5.2
- 6.0
- 6.1 (edge)

## Drop Rails versions (these are not maintained by rails):

- 3.1
- 3.2
- 4.0
- 4.1
- 4.2
- 5.0
- 5.1

In addition, I also have updated Ruby version in travis config:

- 2.4.9
- 2.5.7
- 2.6.5
- 2.7.0

Currently, Ruby 2.3 or ealier series are not supported. So I've dropped them. Thanks.

### CODE REVIEW

**Comment by yhirano55** [comment]
According to [Rails Guide](https://guides.rubyonrails.org/maintenance_policy.html#security-issues), it seems that v4.2 and 5.0 and 5.1 have also already been unsupported versions. So I'm going to drop them in CI config.

**Comment by yhirano55** [comment]
@craigmcnamara I guess this compass-rails is hardly maintained, but some projects (includes our legacy project) still use it, would you please review this patch?

**Comment by yhirano55** [comment]
@scottdavis @chriseppstein Could you review this pull request?

**Comment by prateekkish** [comment]
Bump! Could someone review this PR?

@scottdavis @chriseppstein

**Comment by craigmcnamara** [comment]
It's been years since I've used Compass, but since you guys did the legwork I merge the pull and cut release 4.0.0. You can update your gemfiles and try your handiwork.

**Comment by prateekkish** [comment]
@craigmcnamara I don't see release 4.0 ? The latest here is 3.1.0

**Pull request merged**
