### PR TITLE
Sprockets 3 support

### PR DESCRIPTION
**Pull request by robkilby**
This PR builds upon the work done by @urkle in his fork. I’ve also provided fixes for the lack of Hike in later builds of Sprockets.

All tests are passing locally on both builds of Sprockets 2 and Sprockets 3.

### CODE REVIEW

**Comment by thenanyu** [comment]
We would very much love this over at Everlane. I believe being stuck on an old version of sprockets exposes us to this: https://github.com/sstephenson/sprockets/pull/441

**Comment by eitoball** [comment]
+1 for merging this PR. I am using this branch without any problems.

**Comment by robkilby** [comment]
This should fix #232, #236, and #244 - @craigmcnamara any comments?

**Comment by mib32** [comment]
@robkilby  That's really cool but i get `undefined method `=~' for #<Pathname:../images/icons/categories/animals.png>` when trying to make a sprite!

**Comment by robkilby** [comment]
Thanks for the feedback @mib32. I'll look into the issue over the weekend.

**Comment by mib32** [comment]
@robkilby thanks, i'm also working on this

**Comment by mib32** [comment]
@robkilby Forget that, it is a bug in compass-core, which is already deprecated, so it's impossible to fix. I'll use sprite_factory for my sprites!

**Comment by matsuhisa** [comment]
I also am using this branch without any problems.

**Comment by quiqueg** [comment]
Any update on getting this merged?

**Comment by NealJMD** [comment]
I've been using `gem "compass-rails", git: 'https://github.com/robkilby/compass-rails', branch: 'sprockets-3'` in my Gemfile. It works great, and it would be great to get it merged and released so I can clean that up.

Thanks!

**Comment by PkerUNO** [comment]
Same here, +1 for this PR!

**Comment by CyborgMaster** [comment]
Now that this is merged, can we get a release to RubyGems?

**Comment by quiqueg** [comment]
+1 for a new release

**Comment by rmm5t** [comment]
:+1: New release, please.

**Comment by Davidiusdadi** [comment]
Could it be that Sprockets 3 support is still buggy? See #256

**Comment by aeberlin** [comment]
Could we _please_ get a new release?

**Pull request merged**
