### PR TITLE
Updated Appraisals, Travis CI to confirm gem works in Rails 5

### PR DESCRIPTION
**Pull request by mvastola**
Per [this comment](https://github.com/Compass/compass-rails/issues/254#issuecomment-169908373) in #254, I am submitting this PR to run integration/unit tests with Rails 5 (now in beta), to demonstrate that they are passing, and on this basis, advocate for some sort of release.

### CODE REVIEW

**Comment by mvastola** [comment]
Note: This was testing successfully locally. Not entirely sure what broke here, but I'll fix it in the coming days (hopefully this weekend).

**Comment by mvastola** [comment]
**UPDATE: All tests now passing.**

**Comment by timhaines** [comment]
@mvastola What are your thoughts on a new release that can run in Rails 4.2 with Sprockets 3.x?  Did you see anything that might prevent that?

**Comment by craigmcnamara** [comment]
Compass rails 3.0.0 has been cut.

**Comment by craigmcnamara** [comment]
If you send more pull requests I'll cut more releases.

**Comment by mvastola** [comment]
@timhaines I'm sure since I put in that requirement in the `rails-42` `Appraisal`, I did think I saw something. That said, from a cursory look, I can't seem to find it again right now. I **do** see a limitation preventing `sprockets` 4.0, however. I'll try to update the version constraint on the `Appraisal` and see what `sprockets` version the `Gemfile.lock` resolves to. If it's `>= 3.0`, I'll PR a quick fix.

To be clear though, the fix would only be to the `Appraisals` file (and thus to the `rails42.gemfile` used by Travis CI). If `sprockets` 3.x is indeed compatible with `rails` 4.2, this newly-pushed gem will be compatible with it. The only file in this repository that is controlling regarding dependency versions is `compass-rails.gemspec`, and that is satisfied by any `sprockets` version `< 4.0`.

@craigmcnamara As I stated above, I'll check for @timhaines possible bug and the need for a quick fix, but even assuming its present, it shouldn't warrant cutting a new release (at least, IMHO) as it only affects the version set used by one of the `Appraisals`, and none of the runtime dependency requirements.

**Comment by mvastola** [comment]
Oh, and, @craigmcnamara, of course, thanks for the merge!

**Comment by mvastola** [comment]
Oh, @craigmcnamara, I just closed my issue re: this PR #254, but you can also close #255 (which is a duplicate) by telling them to run `gem update`.

**Comment by mvastola** [comment]
@craigmcnamara I just submitted #260. @timhaines was correct; `rails` 4.2 can run with (and therefore should be tested against) `sprockets` 3.x

**Comment by timhaines** [comment]
@craigmcnamara @mvastola Thanks guys!  Now I just need to figure out what `no implicit conversion of Sprockets::Asset into String` means.  :)

**Comment by mvastola** [comment]
Hm. Ok. Let me know if you trace it back to anything having to do with this commit. (Unlikely, but still.)

**Pull request merged**
