### PR TITLE
Fixed testing regression in 6dc0a83.

### PR DESCRIPTION
**Pull request by mvastola**
Rails 4.2 should be tested against sprockets 3.x.

Issue fixed per [this](https://github.com/Compass/compass-rails/pull/258#issuecomment-174152455) comment by @timhaines in #258.

### CODE REVIEW

**Comment by timhaines** [comment]
😀👍

**Comment by mvastola** [comment]
Oops. Just fixed the commit hash to be correct now. (I just took the most recent commit at the time and didn't realized you had done a second merge after mine.) All better now.

**Comment by craigmcnamara** [comment]
You want a 3.1 release for this since 3.0.0 has been cut?

**Comment by mvastola** [comment]
Nope. No release needed since it only affects the internal tests, I would say. If you do think it warrants a release, I'd only do 3.0.1. This doesn't change the gem's functionality in any way.

**Comment by mvastola** [comment]
If you want my advice, I would do this: Merge this PR. If you expect a new release will be cut (for other reasons) in the next 2 to 3 months or so, don't bother doing a release now. Otherwise, cut a release for 3.0.1.

This change is really only of interest to people making changes to and debugging this gem, who should ideally be working off of the `master` branch in the first place. The important thing is that this PR is merged. Beyond that, whether or not to release is relatively insignificant.

**Comment by craigmcnamara** [comment]
I've mostly gone into hibernation on this gem, but if you're interested in making this work for you I'll promise to be responsive and merge pull requests and cut releases when asked.

**Comment by mvastola** [comment]
Ok. I appreciate it. I haven't used it too much with `rails` 5 yet, but AFAIK, the previous PR was all that was needed to make it work with that. This PR is just fixing a very minor incidental regression I made with that one. I will definitely submit additional PRs if/as any further issues come up.

(Note that I obviously can't speak to the outstanding issues submitted for this and/or confirm if those still exist. If they are confirmed and fixed, additional tests should be added to ensure they don't recur in the future.)

**Pull request merged**
